### ISSUE TITLE
So sad this doesn't work anymore

### ISSUE THREAD

**Issue by iliadaili** [marcospgp/twitter-infinite-scroll-disabler#1]
Hi dude. Do you have any intention and think there's any possibility that you'll be able to make this extension work again? I imagine it's not the case, but I just wanted to be sure. I really wanted this to work, I hate endless scrolling with a passion

**Comment by marcospgp** [comment]
Sorry, no time to dedicate to this. Feel free to submit a pull request!

**Comment by iliadaili** [comment]
I understand. Thanks for the quick answer!
